export interface Project {
  index: number;
  title: string;
  titleMarathi: string;
  form_id: string;
  view_url: string;
  edit_url: string;
  category: string;
  icon: string;
  description: string;
  descriptionMarathi: string;
  active: boolean;
}

export const PROJECTS: Project[] = [
  {
    index: 1,
    title: "CBSE / State School (K12)",
    titleMarathi: "CBSE / राज्य शाळा (K12)",
    form_id: "1MnlKlHt-R57w4mzMAu_oAY6eeoW3PBwrN0AIgkEdOrs",
    view_url: "https://docs.google.com/forms/d/1MnlKlHt-R57w4mzMAu_oAY6eeoW3PBwrN0AIgkEdOrs/viewform",
    edit_url: "https://docs.google.com/forms/d/1MnlKlHt-R57w4mzMAu_oAY6eeoW3PBwrN0AIgkEdOrs/edit",
    category: "Education Campus",
    icon: "🏫",
    description: "Residential CBSE school for Classes 5–12 with 120 students per class",
    descriptionMarathi: "इयत्ता ५ ते १२ साठी निवासी CBSE शाळा, प्रति वर्ग १२० विद्यार्थी",
    active: true,
  },
  {
    index: 2,
    title: "Coaching Center (NEET/JEE/CET)",
    titleMarathi: "कोचिंग सेंटर (NEET/JEE/CET)",
    form_id: "1NZWIi2sDiUHWDYM1zSJsQnbVfVlIXKKF-1qnGluS9Ng",
    view_url: "https://docs.google.com/forms/d/1NZWIi2sDiUHWDYM1zSJsQnbVfVlIXKKF-1qnGluS9Ng/viewform",
    edit_url: "https://docs.google.com/forms/d/1NZWIi2sDiUHWDYM1zSJsQnbVfVlIXKKF-1qnGluS9Ng/edit",
    category: "Education Campus",
    icon: "📚",
    description: "Residential & day coaching for NEET, JEE, MHT-CET aspirants",
    descriptionMarathi: "NEET, JEE, MHT-CET इच्छुकांसाठी निवासी आणि दिवस कोचिंग",
    active: true,
  },
  {
    index: 3,
    title: "Library",
    titleMarathi: "ग्रंथालय",
    form_id: "1_8qksnQmum75rDO5jTSTOr77Cu8gkculFMFymSBXN6k",
    view_url: "https://docs.google.com/forms/d/1_8qksnQmum75rDO5jTSTOr77Cu8gkculFMFymSBXN6k/viewform",
    edit_url: "https://docs.google.com/forms/d/1_8qksnQmum75rDO5jTSTOr77Cu8gkculFMFymSBXN6k/edit",
    category: "Education Campus",
    icon: "📖",
    description: "Central library with digital resources serving the entire campus",
    descriptionMarathi: "संपूर्ण कॅम्पसला सेवा देणारे डिजिटल संसाधनांसह मध्यवर्ती ग्रंथालय",
    active: false,
  },
  {
    index: 4,
    title: "Study Center (UPSC/MPSC)",
    titleMarathi: "अभ्यास केंद्र (UPSC/MPSC)",
    form_id: "1lYeNb6ju9wfmbJmKZd5nTqHaItj-zpzckKkSFofw7L8",
    view_url: "https://docs.google.com/forms/d/1lYeNb6ju9wfmbJmKZd5nTqHaItj-zpzckKkSFofw7L8/viewform",
    edit_url: "https://docs.google.com/forms/d/1lYeNb6ju9wfmbJmKZd5nTqHaItj-zpzckKkSFofw7L8/edit",
    category: "Education Campus",
    icon: "🎯",
    description: "Dedicated center for civil services aspirants — UPSC, MPSC, Police Bharti",
    descriptionMarathi: "नागरी सेवा इच्छुकांसाठी समर्पित केंद्र — UPSC, MPSC, पोलीस भरती",
    active: false,
  },
  {
    index: 5,
    title: "Skill Campus (25–30 Skill Units)",
    titleMarathi: "कौशल्य कॅम्पस (२५–३० कौशल्य युनिट्स)",
    form_id: "1jeVEsQq7EsMazGGmv_AmT9Gxp04fzOVxgGVSLzVtRik",
    view_url: "https://docs.google.com/forms/d/1jeVEsQq7EsMazGGmv_AmT9Gxp04fzOVxgGVSLzVtRik/viewform",
    edit_url: "https://docs.google.com/forms/d/1jeVEsQq7EsMazGGmv_AmT9Gxp04fzOVxgGVSLzVtRik/edit",
    category: "Skill Campus",
    icon: "🛠️",
    description: "25–30 hands-on skill units with training, internships and campus service integration",
    descriptionMarathi: "२५–३० व्यावहारिक कौशल्य युनिट्स — प्रशिक्षण, इंटर्नशिप आणि कॅम्पस सेवा एकत्रीकरण",
    active: false,
  },
  {
    index: 6,
    title: "Software Development Park",
    titleMarathi: "सॉफ्टवेअर डेव्हलपमेंट पार्क",
    form_id: "13GIpsqi5qrCPR1LW7n14CARrqf8R19limTZqHfMWTo0",
    view_url: "https://docs.google.com/forms/d/13GIpsqi5qrCPR1LW7n14CARrqf8R19limTZqHfMWTo0/viewform",
    edit_url: "https://docs.google.com/forms/d/13GIpsqi5qrCPR1LW7n14CARrqf8R19limTZqHfMWTo0/edit",
    category: "Skill Campus",
    icon: "💻",
    description: "Technology park for software training, startups and commercial IT workspace",
    descriptionMarathi: "सॉफ्टवेअर प्रशिक्षण, स्टार्टअप्स आणि व्यावसायिक IT कार्यक्षेत्रासाठी तंत्रज्ञान पार्क",
    active: false,
  },
  {
    index: 7,
    title: "Old Age Home",
    titleMarathi: "वृद्धाश्रम",
    form_id: "1FA89WcDkAX5ndft5nngABw2-HunBnw59-cZzPEtzHcc",
    view_url: "https://docs.google.com/forms/d/1FA89WcDkAX5ndft5nngABw2-HunBnw59-cZzPEtzHcc/viewform",
    edit_url: "https://docs.google.com/forms/d/1FA89WcDkAX5ndft5nngABw2-HunBnw59-cZzPEtzHcc/edit",
    category: "Social Projects",
    icon: "🏡",
    description: "Dignified residential care for senior citizens, integrated with campus community",
    descriptionMarathi: "वृद्ध नागरिकांसाठी सन्माननीय निवासी सेवा, कॅम्पस समुदायाशी एकत्रित",
    active: false,
  },
  {
    index: 8,
    title: "Care Center",
    titleMarathi: "केअर सेंटर",
    form_id: "1VwriXUsaCC42XZ9zsGNtk_4dKBkPfOk33bBT_yWWl2E",
    view_url: "https://docs.google.com/forms/d/1VwriXUsaCC42XZ9zsGNtk_4dKBkPfOk33bBT_yWWl2E/viewform",
    edit_url: "https://docs.google.com/forms/d/1VwriXUsaCC42XZ9zsGNtk_4dKBkPfOk33bBT_yWWl2E/edit",
    category: "Social Projects",
    icon: "🤝",
    description: "Day care for toddlers, special needs children and differently-abled individuals",
    descriptionMarathi: "लहान मुले, विशेष गरजा असलेली मुले आणि अपंग व्यक्तींसाठी डे केअर",
    active: false,
  },
  {
    index: 9,
    title: "Hospital",
    titleMarathi: "रुग्णालय",
    form_id: "18hjbDMhuszTBbyfVqQ8WQituU9UrmOQXX1YanawyijY",
    view_url: "https://docs.google.com/forms/d/18hjbDMhuszTBbyfVqQ8WQituU9UrmOQXX1YanawyijY/viewform",
    edit_url: "https://docs.google.com/forms/d/18hjbDMhuszTBbyfVqQ8WQituU9UrmOQXX1YanawyijY/edit",
    category: "Social Projects",
    icon: "🏥",
    description: "Multi-specialty hospital serving campus and surrounding rural communities",
    descriptionMarathi: "कॅम्पस आणि आसपासच्या ग्रामीण समुदायांना सेवा देणारे बहु-विशेष रुग्णालय",
    active: false,
  },
  {
    index: 10,
    title: "Rural Development Center",
    titleMarathi: "ग्रामीण विकास केंद्र",
    form_id: "1CxFMJ9KOsfHbXvcDVSFHAxlsVxa5to244-oTzNZ4tks",
    view_url: "https://docs.google.com/forms/d/1CxFMJ9KOsfHbXvcDVSFHAxlsVxa5to244-oTzNZ4tks/viewform",
    edit_url: "https://docs.google.com/forms/d/1CxFMJ9KOsfHbXvcDVSFHAxlsVxa5to244-oTzNZ4tks/edit",
    category: "Social Projects",
    icon: "🌾",
    description: "Empowering villages through farmer education, women's programs and digital literacy",
    descriptionMarathi: "शेतकरी शिक्षण, महिला कार्यक्रम आणि डिजिटल साक्षरतेद्वारे गावांचे सशक्तीकरण",
    active: false,
  },
  {
    index: 11,
    title: "Training Center",
    titleMarathi: "प्रशिक्षण केंद्र",
    form_id: "19fQqaqL5DKg5V3UoaRnbt_4jZ4tQE3flcO-72FkpgNk",
    view_url: "https://docs.google.com/forms/d/19fQqaqL5DKg5V3UoaRnbt_4jZ4tQE3flcO-72FkpgNk/viewform",
    edit_url: "https://docs.google.com/forms/d/19fQqaqL5DKg5V3UoaRnbt_4jZ4tQE3flcO-72FkpgNk/edit",
    category: "Social Projects",
    icon: "🎓",
    description: "Corporate, leadership and government staff training with conference facilities",
    descriptionMarathi: "कॉर्पोरेट, नेतृत्व आणि सरकारी कर्मचारी प्रशिक्षण — परिषद सुविधांसह",
    active: false,
  },
  {
    index: 12,
    title: "Cricket & Football Ground",
    titleMarathi: "क्रिकेट आणि फुटबॉल मैदान",
    form_id: "1MEuKM9YJQN2ZogzAzy9wvxuuWdQMxhm0UzDpscB5MHw",
    view_url: "https://docs.google.com/forms/d/1MEuKM9YJQN2ZogzAzy9wvxuuWdQMxhm0UzDpscB5MHw/viewform",
    edit_url: "https://docs.google.com/forms/d/1MEuKM9YJQN2ZogzAzy9wvxuuWdQMxhm0UzDpscB5MHw/edit",
    category: "Sport & Cultural Center",
    icon: "🏏",
    description: "Full-size cricket and football grounds with coaching academy potential",
    descriptionMarathi: "कोचिंग अकादमीच्या संभाव्यतेसह पूर्ण आकाराचे क्रिकेट आणि फुटबॉल मैदान",
    active: false,
  },
  {
    index: 13,
    title: "Indoor Games Facility",
    titleMarathi: "इनडोअर गेम्स सुविधा",
    form_id: "1exFVU7oZMbTVsksVTutkqMgJFwKqN05bPuSYLbq6H_Y",
    view_url: "https://docs.google.com/forms/d/1exFVU7oZMbTVsksVTutkqMgJFwKqN05bPuSYLbq6H_Y/viewform",
    edit_url: "https://docs.google.com/forms/d/1exFVU7oZMbTVsksVTutkqMgJFwKqN05bPuSYLbq6H_Y/edit",
    category: "Sport & Cultural Center",
    icon: "🏸",
    description: "Multi-sport indoor hall for badminton, table tennis, boxing and more",
    descriptionMarathi: "बॅडमिंटन, टेबल टेनिस, बॉक्सिंग आणि अधिकसाठी बहु-क्रीडा इनडोअर हॉल",
    active: false,
  },
  {
    index: 14,
    title: "Gymnasium & Swimming Pool",
    titleMarathi: "जिम्नॅशियम आणि जलतरण तलाव",
    form_id: "1wj3eNSu1W8lI01ejMjL1yf2wgh0YOsgFBEPcX1r_1ic",
    view_url: "https://docs.google.com/forms/d/1wj3eNSu1W8lI01ejMjL1yf2wgh0YOsgFBEPcX1r_1ic/viewform",
    edit_url: "https://docs.google.com/forms/d/1wj3eNSu1W8lI01ejMjL1yf2wgh0YOsgFBEPcX1r_1ic/edit",
    category: "Sport & Cultural Center",
    icon: "🏊",
    description: "Modern gymnasium and swimming pool for students, staff and residents",
    descriptionMarathi: "विद्यार्थी, कर्मचारी आणि रहिवाशांसाठी आधुनिक जिम्नॅशियम आणि जलतरण तलाव",
    active: false,
  },
  {
    index: 15,
    title: "Residential Bungalow Complex",
    titleMarathi: "निवासी बंगला संकुल",
    form_id: "1-EHU9I29k6X5yjCxQLCJOpYYjnx5-A9PCNjfHBsU6hY",
    view_url: "https://docs.google.com/forms/d/1-EHU9I29k6X5yjCxQLCJOpYYjnx5-A9PCNjfHBsU6hY/viewform",
    edit_url: "https://docs.google.com/forms/d/1-EHU9I29k6X5yjCxQLCJOpYYjnx5-A9PCNjfHBsU6hY/edit",
    category: "Residential Community",
    icon: "🏘️",
    description: "200–250 gated bungalow plots for like-minded families in nature",
    descriptionMarathi: "निसर्गात समान विचारसरणीच्या कुटुंबांसाठी २००–२५० गेटेड बंगला भूखंड",
    active: false,
  },
  {
    index: 16,
    title: "Clubhouse",
    titleMarathi: "क्लबहाऊस",
    form_id: "1i6VK_vuIeK-1-EFACEDLNQjtb9ZYECRzGCWOcpmREHQ",
    view_url: "https://docs.google.com/forms/d/1i6VK_vuIeK-1-EFACEDLNQjtb9ZYECRzGCWOcpmREHQ/viewform",
    edit_url: "https://docs.google.com/forms/d/1i6VK_vuIeK-1-EFACEDLNQjtb9ZYECRzGCWOcpmREHQ/edit",
    category: "Residential Community",
    icon: "🎪",
    description: "Premium social club with dining, recreation and event facilities",
    descriptionMarathi: "जेवण, मनोरंजन आणि कार्यक्रम सुविधांसह प्रीमियम सामाजिक क्लब",
    active: false,
  },
  {
    index: 17,
    title: "Agriculture & Horticulture",
    titleMarathi: "शेती आणि फलोत्पादन",
    form_id: "1M3nFzxurBp8u6jVgP75YNRdkTvxGeA5U5VwfCAUU5s0",
    view_url: "https://docs.google.com/forms/d/1M3nFzxurBp8u6jVgP75YNRdkTvxGeA5U5VwfCAUU5s0/viewform",
    edit_url: "https://docs.google.com/forms/d/1M3nFzxurBp8u6jVgP75YNRdkTvxGeA5U5VwfCAUU5s0/edit",
    category: "Sustainability",
    icon: "🌿",
    description: "Organic farm, orchards and training plots for self-sufficient campus food",
    descriptionMarathi: "आत्मनिर्भर कॅम्पस अन्नासाठी सेंद्रिय शेत, फळबागा आणि प्रशिक्षण भूखंड",
    active: false,
  },
  {
    index: 18,
    title: "Animal Husbandry",
    titleMarathi: "पशुपालन",
    form_id: "1C3Mf880MLEUdUPl5tWa6iWsrhuXZ1GiNp3ZmInzmFJg",
    view_url: "https://docs.google.com/forms/d/1C3Mf880MLEUdUPl5tWa6iWsrhuXZ1GiNp3ZmInzmFJg/viewform",
    edit_url: "https://docs.google.com/forms/d/1C3Mf880MLEUdUPl5tWa6iWsrhuXZ1GiNp3ZmInzmFJg/edit",
    category: "Sustainability",
    icon: "🐄",
    description: "Dairy, poultry and aquaculture for campus food supply and skill training",
    descriptionMarathi: "कॅम्पस अन्न पुरवठा आणि कौशल्य प्रशिक्षणासाठी दुग्धव्यवसाय, कुक्कुटपालन आणि जलसंवर्धन",
    active: false,
  },
  {
    index: 19,
    title: "Campus Canteen & Food Services",
    titleMarathi: "कॅम्पस कॅन्टीन आणि अन्न सेवा",
    form_id: "1l-yAQroO1kjIT8-0QNIIcvNLv7PIr3-JWOPcohgq8YE",
    view_url: "https://docs.google.com/forms/d/1l-yAQroO1kjIT8-0QNIIcvNLv7PIr3-JWOPcohgq8YE/viewform",
    edit_url: "https://docs.google.com/forms/d/1l-yAQroO1kjIT8-0QNIIcvNLv7PIr3-JWOPcohgq8YE/edit",
    category: "Sustainability",
    icon: "🍽️",
    description: "Cashless Deepa Coin-based dining for 3,000+ residents and students",
    descriptionMarathi: "३,०००+ रहिवासी आणि विद्यार्थ्यांसाठी कॅशलेस दीपा कॉईन-आधारित जेवण",
    active: false,
  },
  {
    index: 20,
    title: "Internal Roads & Infrastructure",
    titleMarathi: "अंतर्गत रस्ते आणि पायाभूत सुविधा",
    form_id: "1j8HzWPfVYr2oHDeNFoaHEmUBQweQMgIewzoaRwog5AI",
    view_url: "https://docs.google.com/forms/d/1j8HzWPfVYr2oHDeNFoaHEmUBQweQMgIewzoaRwog5AI/viewform",
    edit_url: "https://docs.google.com/forms/d/1j8HzWPfVYr2oHDeNFoaHEmUBQweQMgIewzoaRwog5AI/edit",
    category: "Infrastructure",
    icon: "🛣️",
    description: "Roads, utilities, solar power, water, sewage and campus-wide digital network",
    descriptionMarathi: "रस्ते, उपयुक्तता, सौर ऊर्जा, पाणी, सांडपाणी आणि कॅम्पसव्यापी डिजिटल नेटवर्क",
    active: false,
  },
];

export const CATEGORIES = [
  "Education Campus",
  "Skill Campus",
  "Social Projects",
  "Sport & Cultural Center",
  "Residential Community",
  "Sustainability",
  "Infrastructure",
];
