export interface Project {
  index: number;
  title: string;
  titleMarathi: string;
  form_id: string;
  view_url: string;
  edit_url: string;
  category: string;
  icon: string;
  description: string;
  descriptionMarathi: string;
  active: boolean;
}

export const PROJECTS: Project[] = [
  {
    index: 1,
    title: "CBSE / State School (K12)",
    titleMarathi: "CBSE / राज्य शाळा (K12)",
    form_id: "13k2KsC3QQ-a05JW7sY9bP1zlM1UUiIT9iBT5DzobQC8",
    view_url: "https://docs.google.com/forms/d/13k2KsC3QQ-a05JW7sY9bP1zlM1UUiIT9iBT5DzobQC8/viewform",
    edit_url: "https://docs.google.com/forms/d/13k2KsC3QQ-a05JW7sY9bP1zlM1UUiIT9iBT5DzobQC8/edit",
    category: "Education Campus",
    icon: "🏫",
    description: "Residential CBSE school for Classes 5–12 with 120 students per class",
    descriptionMarathi: "इयत्ता ५ ते १२ साठी निवासी CBSE शाळा, प्रति वर्ग १२० विद्यार्थी",
    active: true,
  },
  {
    index: 2,
    title: "Coaching Center (NEET/JEE/CET)",
    titleMarathi: "कोचिंग सेंटर (NEET/JEE/CET)",
    form_id: "1d2rwg0VX-8tuLCuEorGmQ1fpqKMjMx_eRYlI93sUuqY",
    view_url: "https://docs.google.com/forms/d/1d2rwg0VX-8tuLCuEorGmQ1fpqKMjMx_eRYlI93sUuqY/viewform",
    edit_url: "https://docs.google.com/forms/d/1d2rwg0VX-8tuLCuEorGmQ1fpqKMjMx_eRYlI93sUuqY/edit",
    category: "Education Campus",
    icon: "📚",
    description: "Residential & day coaching for NEET, JEE, MHT-CET aspirants",
    descriptionMarathi: "NEET, JEE, MHT-CET इच्छुकांसाठी निवासी आणि दिवस कोचिंग",
    active: true,
  },
  {
    index: 3,
    title: "Library",
    titleMarathi: "ग्रंथालय",
    form_id: "1YH5J8Bigf8YIJLBDFWTq3hYZuYBnf02Dw-dhEJhG_0g",
    view_url: "https://docs.google.com/forms/d/1YH5J8Bigf8YIJLBDFWTq3hYZuYBnf02Dw-dhEJhG_0g/viewform",
    edit_url: "https://docs.google.com/forms/d/1YH5J8Bigf8YIJLBDFWTq3hYZuYBnf02Dw-dhEJhG_0g/edit",
    category: "Education Campus",
    icon: "📖",
    description: "Central library with digital resources serving the entire campus",
    descriptionMarathi: "संपूर्ण कॅम्पसला सेवा देणारे डिजिटल संसाधनांसह मध्यवर्ती ग्रंथालय",
    active: false,
  },
  {
    index: 4,
    title: "Study Center (UPSC/MPSC)",
    titleMarathi: "अभ्यास केंद्र (UPSC/MPSC)",
    form_id: "1G4wdaV_m5BJ6uuNnVdVfgI_-U7o1W_C93VGWa4iTGaQ",
    view_url: "https://docs.google.com/forms/d/1G4wdaV_m5BJ6uuNnVdVfgI_-U7o1W_C93VGWa4iTGaQ/viewform",
    edit_url: "https://docs.google.com/forms/d/1G4wdaV_m5BJ6uuNnVdVfgI_-U7o1W_C93VGWa4iTGaQ/edit",
    category: "Education Campus",
    icon: "🎯",
    description: "Dedicated center for civil services aspirants — UPSC, MPSC, Police Bharti",
    descriptionMarathi: "नागरी सेवा इच्छुकांसाठी समर्पित केंद्र — UPSC, MPSC, पोलीस भरती",
    active: false,
  },
  {
    index: 5,
    title: "Skill Campus (25–30 Skill Units)",
    titleMarathi: "कौशल्य कॅम्पस (२५–३० कौशल्य युनिट्स)",
    form_id: "1jJLzMZOav4oVz8RgpmFsbqBYRd5QDb2pNCCy--nGz8Q",
    view_url: "https://docs.google.com/forms/d/1jJLzMZOav4oVz8RgpmFsbqBYRd5QDb2pNCCy--nGz8Q/viewform",
    edit_url: "https://docs.google.com/forms/d/1jJLzMZOav4oVz8RgpmFsbqBYRd5QDb2pNCCy--nGz8Q/edit",
    category: "Skill Campus",
    icon: "🛠️",
    description: "25–30 hands-on skill units with training, internships and campus service integration",
    descriptionMarathi: "२५–३० व्यावहारिक कौशल्य युनिट्स — प्रशिक्षण, इंटर्नशिप आणि कॅम्पस सेवा एकत्रीकरण",
    active: false,
  },
  {
    index: 6,
    title: "Software Development Park",
    titleMarathi: "सॉफ्टवेअर डेव्हलपमेंट पार्क",
    form_id: "1nbqkDMxhcEUMIWkQ4aH1-OmNrcOOl4p1vbMhdZdU7lk",
    view_url: "https://docs.google.com/forms/d/1nbqkDMxhcEUMIWkQ4aH1-OmNrcOOl4p1vbMhdZdU7lk/viewform",
    edit_url: "https://docs.google.com/forms/d/1nbqkDMxhcEUMIWkQ4aH1-OmNrcOOl4p1vbMhdZdU7lk/edit",
    category: "Skill Campus",
    icon: "💻",
    description: "Technology park for software training, startups and commercial IT workspace",
    descriptionMarathi: "सॉफ्टवेअर प्रशिक्षण, स्टार्टअप्स आणि व्यावसायिक IT कार्यक्षेत्रासाठी तंत्रज्ञान पार्क",
    active: false,
  },
  {
    index: 7,
    title: "Old Age Home",
    titleMarathi: "वृद्धाश्रम",
    form_id: "1y-xYe_yvhSTZJ8DbXQ1Ie7RRodTLDs2a682PhRIodrA",
    view_url: "https://docs.google.com/forms/d/1y-xYe_yvhSTZJ8DbXQ1Ie7RRodTLDs2a682PhRIodrA/viewform",
    edit_url: "https://docs.google.com/forms/d/1y-xYe_yvhSTZJ8DbXQ1Ie7RRodTLDs2a682PhRIodrA/edit",
    category: "Social Projects",
    icon: "🏡",
    description: "Dignified residential care for senior citizens, integrated with campus community",
    descriptionMarathi: "वृद्ध नागरिकांसाठी सन्माननीय निवासी सेवा, कॅम्पस समुदायाशी एकत्रित",
    active: false,
  },
  {
    index: 8,
    title: "Care Center",
    titleMarathi: "केअर सेंटर",
    form_id: "1ulAtFQE_-QDeTMtNnIYXWBPG1a-fY8sMmADtPK-9SAM",
    view_url: "https://docs.google.com/forms/d/1ulAtFQE_-QDeTMtNnIYXWBPG1a-fY8sMmADtPK-9SAM/viewform",
    edit_url: "https://docs.google.com/forms/d/1ulAtFQE_-QDeTMtNnIYXWBPG1a-fY8sMmADtPK-9SAM/edit",
    category: "Social Projects",
    icon: "🤝",
    description: "Day care for toddlers, special needs children and differently-abled individuals",
    descriptionMarathi: "लहान मुले, विशेष गरजा असलेली मुले आणि अपंग व्यक्तींसाठी डे केअर",
    active: false,
  },
  {
    index: 9,
    title: "Hospital",
    titleMarathi: "रुग्णालय",
    form_id: "1cfYBsE43ELqYcLDqn24Bz51kw4M1PJNdS4xeiDlF05c",
    view_url: "https://docs.google.com/forms/d/1cfYBsE43ELqYcLDqn24Bz51kw4M1PJNdS4xeiDlF05c/viewform",
    edit_url: "https://docs.google.com/forms/d/1cfYBsE43ELqYcLDqn24Bz51kw4M1PJNdS4xeiDlF05c/edit",
    category: "Social Projects",
    icon: "🏥",
    description: "Multi-specialty hospital serving campus and surrounding rural communities",
    descriptionMarathi: "कॅम्पस आणि आसपासच्या ग्रामीण समुदायांना सेवा देणारे बहु-विशेष रुग्णालय",
    active: false,
  },
  {
    index: 10,
    title: "Rural Development Center",
    titleMarathi: "ग्रामीण विकास केंद्र",
    form_id: "1-HCDDY68Zuz2Fs928LzDRjO96kmgSlzaVt_0Bi32QDw",
    view_url: "https://docs.google.com/forms/d/1-HCDDY68Zuz2Fs928LzDRjO96kmgSlzaVt_0Bi32QDw/viewform",
    edit_url: "https://docs.google.com/forms/d/1-HCDDY68Zuz2Fs928LzDRjO96kmgSlzaVt_0Bi32QDw/edit",
    category: "Social Projects",
    icon: "🌾",
    description: "Empowering villages through farmer education, women's programs and digital literacy",
    descriptionMarathi: "शेतकरी शिक्षण, महिला कार्यक्रम आणि डिजिटल साक्षरतेद्वारे गावांचे सशक्तीकरण",
    active: false,
  },
  {
    index: 11,
    title: "Training Center",
    titleMarathi: "प्रशिक्षण केंद्र",
    form_id: "1OBr-D1UTpPM2cwduQp1IQds4YMRJllhyennl8bcsdJw",
    view_url: "https://docs.google.com/forms/d/1OBr-D1UTpPM2cwduQp1IQds4YMRJllhyennl8bcsdJw/viewform",
    edit_url: "https://docs.google.com/forms/d/1OBr-D1UTpPM2cwduQp1IQds4YMRJllhyennl8bcsdJw/edit",
    category: "Social Projects",
    icon: "🎓",
    description: "Corporate, leadership and government staff training with conference facilities",
    descriptionMarathi: "कॉर्पोरेट, नेतृत्व आणि सरकारी कर्मचारी प्रशिक्षण — परिषद सुविधांसह",
    active: false,
  },
  {
    index: 12,
    title: "Cricket & Football Ground",
    titleMarathi: "क्रिकेट आणि फुटबॉल मैदान",
    form_id: "11uunF87kv9NH8PqE6OF6MnZKC01oDauLsTJmuPy7SL8",
    view_url: "https://docs.google.com/forms/d/11uunF87kv9NH8PqE6OF6MnZKC01oDauLsTJmuPy7SL8/viewform",
    edit_url: "https://docs.google.com/forms/d/11uunF87kv9NH8PqE6OF6MnZKC01oDauLsTJmuPy7SL8/edit",
    category: "Sport & Cultural Center",
    icon: "🏏",
    description: "Full-size cricket and football grounds with coaching academy potential",
    descriptionMarathi: "कोचिंग अकादमीच्या संभाव्यतेसह पूर्ण आकाराचे क्रिकेट आणि फुटबॉल मैदान",
    active: false,
  },
  {
    index: 13,
    title: "Indoor Games Facility",
    titleMarathi: "इनडोअर गेम्स सुविधा",
    form_id: "1LzzXBj7GIJbEd08mv9Al4TPDRm0d21mDIHof8Pa1UHI",
    view_url: "https://docs.google.com/forms/d/1LzzXBj7GIJbEd08mv9Al4TPDRm0d21mDIHof8Pa1UHI/viewform",
    edit_url: "https://docs.google.com/forms/d/1LzzXBj7GIJbEd08mv9Al4TPDRm0d21mDIHof8Pa1UHI/edit",
    category: "Sport & Cultural Center",
    icon: "🏸",
    description: "Multi-sport indoor hall for badminton, table tennis, boxing and more",
    descriptionMarathi: "बॅडमिंटन, टेबल टेनिस, बॉक्सिंग आणि अधिकसाठी बहु-क्रीडा इनडोअर हॉल",
    active: false,
  },
  {
    index: 14,
    title: "Gymnasium & Swimming Pool",
    titleMarathi: "जिम्नॅशियम आणि जलतरण तलाव",
    form_id: "1DWnaktVQh4teXw_QeTZgft-A2Ofzj4gL1mOQRIjC3hM",
    view_url: "https://docs.google.com/forms/d/1DWnaktVQh4teXw_QeTZgft-A2Ofzj4gL1mOQRIjC3hM/viewform",
    edit_url: "https://docs.google.com/forms/d/1DWnaktVQh4teXw_QeTZgft-A2Ofzj4gL1mOQRIjC3hM/edit",
    category: "Sport & Cultural Center",
    icon: "🏊",
    description: "Modern gymnasium and swimming pool for students, staff and residents",
    descriptionMarathi: "विद्यार्थी, कर्मचारी आणि रहिवाशांसाठी आधुनिक जिम्नॅशियम आणि जलतरण तलाव",
    active: false,
  },
  {
    index: 15,
    title: "Residential Bungalow Complex",
    titleMarathi: "निवासी बंगला संकुल",
    form_id: "1cGj8dxj2tO7wwUsEfIbyvo5ZsbcRPN1iT69tvJfRi1I",
    view_url: "https://docs.google.com/forms/d/1cGj8dxj2tO7wwUsEfIbyvo5ZsbcRPN1iT69tvJfRi1I/viewform",
    edit_url: "https://docs.google.com/forms/d/1cGj8dxj2tO7wwUsEfIbyvo5ZsbcRPN1iT69tvJfRi1I/edit",
    category: "Residential Community",
    icon: "🏘️",
    description: "200–250 gated bungalow plots for like-minded families in nature",
    descriptionMarathi: "निसर्गात समान विचारसरणीच्या कुटुंबांसाठी २००–२५० गेटेड बंगला भूखंड",
    active: false,
  },
  {
    index: 16,
    title: "Clubhouse",
    titleMarathi: "क्लबहाऊस",
    form_id: "1d5cxIPOBHR22XyC7-Sjx2gGUrnj4Wi_1Ypd0X625Pu8",
    view_url: "https://docs.google.com/forms/d/1d5cxIPOBHR22XyC7-Sjx2gGUrnj4Wi_1Ypd0X625Pu8/viewform",
    edit_url: "https://docs.google.com/forms/d/1d5cxIPOBHR22XyC7-Sjx2gGUrnj4Wi_1Ypd0X625Pu8/edit",
    category: "Residential Community",
    icon: "🎪",
    description: "Premium social club with dining, recreation and event facilities",
    descriptionMarathi: "जेवण, मनोरंजन आणि कार्यक्रम सुविधांसह प्रीमियम सामाजिक क्लब",
    active: false,
  },
  {
    index: 17,
    title: "Agriculture & Horticulture",
    titleMarathi: "शेती आणि फलोत्पादन",
    form_id: "1nFCSOBWTESj53seKBgiwcQFhWJmR-Zv3U8jl33tJ6mE",
    view_url: "https://docs.google.com/forms/d/1nFCSOBWTESj53seKBgiwcQFhWJmR-Zv3U8jl33tJ6mE/viewform",
    edit_url: "https://docs.google.com/forms/d/1nFCSOBWTESj53seKBgiwcQFhWJmR-Zv3U8jl33tJ6mE/edit",
    category: "Sustainability",
    icon: "🌿",
    description: "Organic farm, orchards and training plots for self-sufficient campus food",
    descriptionMarathi: "आत्मनिर्भर कॅम्पस अन्नासाठी सेंद्रिय शेत, फळबागा आणि प्रशिक्षण भूखंड",
    active: false,
  },
  {
    index: 18,
    title: "Animal Husbandry",
    titleMarathi: "पशुपालन",
    form_id: "1l38HN8XOttYMTjY-bJF3O-cQRfvWIJL4F9fqgHq6smE",
    view_url: "https://docs.google.com/forms/d/1l38HN8XOttYMTjY-bJF3O-cQRfvWIJL4F9fqgHq6smE/viewform",
    edit_url: "https://docs.google.com/forms/d/1l38HN8XOttYMTjY-bJF3O-cQRfvWIJL4F9fqgHq6smE/edit",
    category: "Sustainability",
    icon: "🐄",
    description: "Dairy, poultry and aquaculture for campus food supply and skill training",
    descriptionMarathi: "कॅम्पस अन्न पुरवठा आणि कौशल्य प्रशिक्षणासाठी दुग्धव्यवसाय, कुक्कुटपालन आणि जलसंवर्धन",
    active: false,
  },
  {
    index: 19,
    title: "Campus Canteen & Food Services",
    titleMarathi: "कॅम्पस कॅन्टीन आणि अन्न सेवा",
    form_id: "1BhnwbJyaA9b2tV61Rs8yq48jmukLyAeki1VyLspEw3k",
    view_url: "https://docs.google.com/forms/d/1BhnwbJyaA9b2tV61Rs8yq48jmukLyAeki1VyLspEw3k/viewform",
    edit_url: "https://docs.google.com/forms/d/1BhnwbJyaA9b2tV61Rs8yq48jmukLyAeki1VyLspEw3k/edit",
    category: "Sustainability",
    icon: "🍽️",
    description: "Cashless Deepa Coin-based dining for 3,000+ residents and students",
    descriptionMarathi: "३,०००+ रहिवासी आणि विद्यार्थ्यांसाठी कॅशलेस दीपा कॉईन-आधारित जेवण",
    active: false,
  },
  {
    index: 20,
    title: "Internal Roads & Infrastructure",
    titleMarathi: "अंतर्गत रस्ते आणि पायाभूत सुविधा",
    form_id: "1Yw-TiLqfZZ86ElZEIlKl28yWrTX5vKx933KjQvEkdyY",
    view_url: "https://docs.google.com/forms/d/1Yw-TiLqfZZ86ElZEIlKl28yWrTX5vKx933KjQvEkdyY/viewform",
    edit_url: "https://docs.google.com/forms/d/1Yw-TiLqfZZ86ElZEIlKl28yWrTX5vKx933KjQvEkdyY/edit",
    category: "Infrastructure",
    icon: "🛣️",
    description: "Roads, utilities, solar power, water, sewage and campus-wide digital network",
    descriptionMarathi: "रस्ते, उपयुक्तता, सौर ऊर्जा, पाणी, सांडपाणी आणि कॅम्पसव्यापी डिजिटल नेटवर्क",
    active: false,
  },
];

export const CATEGORIES = [
  "Education Campus",
  "Skill Campus",
  "Social Projects",
  "Sport & Cultural Center",
  "Residential Community",
  "Sustainability",
  "Infrastructure",
];
